### ISSUE TITLE
v0.4 Release Tracking Issue

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1517]
This issue is to give context to the community on the progress being made towards v0.4 release.

### Timeline

v0.4 will release on **March 9th, 2022**.

[v0.4 GitHub Project Milestone](https://github.com/awslabs/autogluon/milestone/6)

### Description

v0.4 contains many new features and optimizations. The full list of new features and improvements will be provided in the v0.4 release notes.

####  Windows OS Support
Windows OS will be supported with both CPU and GPU functionality starting in v0.4. Note that performance optimizations are not tested as thoroughly on Windows, so Linux is still the recommendation if speed is critical. If you are interesting in testing Windows on v0.4 pre-release, the install instructions are available here: https://auto.gluon.ai/dev/index.html.

#### Python 3.9 Support
We are adding Python 3.9 Support and dropping Python 3.6 support in v0.4. This means AutoGluon v0.4 will be available on Python 3.7, 3.8, and 3.9. AutoGluon does not yet support Python 3.10.

#### HuggingFace Integration / Torch Migration / Multi-lingual Models
We are refactoring `autogluon.text` to use Torch and HuggingFace as the training backend starting in v0.4. This will enable a much larger selection of models to train with, including multi-lingual models.

#### Parallel Model Training
We are introducing Ray-based parallel model training in v0.4 for model bagging and stacking in `autogluon.tabular`. This feature speeds up end-to-end training by ~2x on average, halving training time compared to v0.3 while using the same hardware.

#### Inference Speed Optimizations 
Many optimizations have been made for both batch inference and online inference.
- Overall TabularPredictor best-quality average batch inference speed accelerated by 60%
- XGBoost batch inference speed accelerated by 500%
- Tabular Neural Network online inference speed accelerated by 1000%, batch inference speed accelerated by 400%
- Linear Model batch inference speed accelerated by 1000%
- Random Forest online inference speed accelerated by 1000%

### Themes and Major Features

- [x] Windows OS Support
- [x] Python 3.9 Support
- [x] HuggingFace Integration
- [x] Torch Migration (Remove MXNet dependency)
- [x] Multi-lingual Language Models
- [x] Parallel Model Training (2x training speed-up for bagging/stacking)
- [x] Inference Speed Optimizations 
- [x] Automated Feature Pruning/Selection
- [x] Semi-supervised & Transductive Learning Support
- [x] Automated Model Calibration via Temperature Scaling
- [x] Adaptive Early Stopping 
- [x] Cloud Training & Deployment Tutorials
- [x] Feature Preprocessing Tutorial
- [x] Documentation Overhaul
- [x] Hyperparameter Tuning Overhaul
- [x] Memory Usage Optimizations
- [x] New Model: VowpalWabbit
- [x] Intel sklearnex backend for Random Forest
- [x] Intel sklearnex backend for Linear Regression
- [x] Improved datetime Feature Handling 
- [x] Various Performance Optimizations
- [x] Various Bug Fixes
