### ISSUE TITLE
[BUG] Ray-based Tuning Optimization

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#2069]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

NOTE: Despite all these issues, ray based tuning is still much better than custom tuning *IF* enough time is specified by the user. The majority of these issues are mostly relevant when small amounts of time are given, such that we can't do many HPO trials. For example, with bagging disabled on 64 CPUs, fastai HPO can train 200 trials with ray in the same time custom HPO can train 5 trials, and ray gets a significantly better test score too due to the sheer amount of trials trained.

**Describe the bug**

- [x] (Fixed in https://github.com/awslabs/autogluon/pull/2133)1. #2068

- [x] (Mostly fixed in #2121) 2. Ray based Tuning kills trials that haven't finished training instead of early stopping them. Custom Tuning early stops trials instead of killing them.

> This situation is tricky because it can sometimes be good to kill them to avoid wasting resource bagging them in the bagging mode. If we were to implement a solution to issue 5 then making things early stop instead of kill would no longer be a problem.

- [x] (Fixed in #2094) 3. Ray based Tuning with FASTAI logs many warnings. Custom Tuning does not.
> NaN or Inf found in input tensor.
NaN or Inf found in input tensor.
NaN or Inf found in input tensor.

- [x] (Fixed in #2094) 4. Ray based Tuning with FASTAI does not tune `layers` hyperparameter (or it doesn't report it properly if it does). Custom Tuning does.

> Example warning log:
> 2022-08-25 01:52:37,376	INFO logger.py:727 -- Removed the following hyperparameter values when logging to tensorboard: {'layers': (50, 25)}
2022-08-25 01:52:37,403	INFO logger.py:727 -- Removed the following hyperparameter values when logging to tensorboard: {'layers': (500,)}
2022-08-25 01:52:37,430	INFO logger.py:727 -- Removed the following hyperparameter values when logging to tensorboard: {'layers': (200, 100)}

- [x] (Fixed in #2121) 5. Ray based Tuning can underestimate training time required when using bagging. Custom Tuning does not.

> Bagging + HPO works as follows in current AG: Fit the first fold of each bag trial during HPO, with a time limit for HPO of 1/8th of the total time (if num_bag_folds=8). Then after 1/8th of time has been used, exit HPO. Then use the 7/8ths remaining time to sequentially fit the remaining 7 folds of each HPO trial bag (with the 7 folds being training in parallel).
> Custom Tuning overestimates training time because HPO is sequential and bagging is parallel, so bagging is faster to train each model than HPO.
> However, Ray Tuning is parallel in both HPO and bagging. If # cpu cores > num bags, then HPO will be faster than bagging per model, so will run out of time when bagging the HPO trained models and some of them won't be used.
> This can be fixed by doing bagging during HPO. However, this will make the code more complex, since you will have to split CPU cores among both bagging and HPO, example with 64 cores and 8 num_bags, each HPO trial gets 8 CPU cores, each trial creates 8 processes with 1 CPU core for each of the 8 bags, thus training 64 models at once (8 trials with 8 bags each).
> Alternatively, each bag gets 1 CPU core (64 trials, 1 CPU core each), then each model in the bag is trained sequentially with 1 core. This allows for the code to be minimally altered and work, but fails drastically if 1 core is too slow given the time limit to train 8 models fully sequentially and is strictly worse than an ideal implementation of training all bag folds in parallel for each trial.

**To Reproduce**

Run the following code on a linux machine and refer to the `hyperparameters` column of the leaderboard output to identify that the defaults are not used. You will also see the warnings for 3 and 4. The other issues are more complex and require code deep dives to understand properly.

```python3
from autogluon.tabular import TabularPredictor, TabularDataset


if __name__ == '__main__':
    path_prefix = 'https://autogluon.s3.amazonaws.com/datasets/AdultIncomeBinaryClassification/'
    path_train = path_prefix + 'train_data.csv'
    path_test = path_prefix + 'test_data.csv'

    label = 'class'
    sample = None  # Number of rows to use to train / infer
    train_data = TabularDataset(path_train)

    if sample is not None and (sample < len(train_data)):
        train_data = train_data.sample(n=sample, random_state=0).reset_index(drop=True)

    test_data = TabularDataset(path_test)

    fit_kwargs = dict(
        train_data=train_data,
        hyperparameters={
            'FASTAI': {},
        },
        # num_bag_folds=8,
        # num_bag_sets=1,
        time_limit=120,
        hyperparameter_tune_kwargs='auto',
    )
    predictor = TabularPredictor(
        label=label,
        eval_metric='roc_auc',
    )
    predictor.fit(**fit_kwargs)

    leaderboard = predictor.leaderboard(test_data, extra_info=True)
```

**Installed Versions**
<details>

```python
INSTALLED VERSIONS
------------------
date                   : 2022-08-25
time                   : 02:11:50.767734
python                 : 3.8.13.final.0
OS                     : Linux
OS-release             : 5.15.0-1017-aws
Version                : #21~20.04.1-Ubuntu SMP Fri Aug 5 11:44:14 UTC 2022
machine                : x86_64
processor              : x86_64
num_cores              : 64
cpu_ram_mb             : 253689
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 1953310

autogluon.cloud        : None
autogluon.common       : 0.5.3b20220824
autogluon.core         : 0.5.3b20220824
autogluon.features     : 0.5.3b20220824
autogluon.multimodal   : 0.5.3b20220824
autogluon.tabular      : 0.5.3b20220824
autogluon.text         : 0.5.3b20220824
autogluon.timeseries   : None
autogluon.vision       : 0.5.3b20220824
autogluon_contrib_nlp  : None
boto3                  : 1.21.21
catboost               : 1.0.6
dask                   : 2021.11.2
distributed            : 2021.11.2
fairscale              : 0.4.6
fastai                 : 2.7.9
gluoncv                : 0.11.0
hyperopt               : 0.2.7
lightgbm               : 3.3.2
matplotlib             : 3.5.3
networkx               : 2.8.6
nlpaug                 : 1.1.10
nltk                   : 3.7
nptyping               : 1.4.4
numpy                  : 1.22.4
omegaconf              : 2.1.2
openmim                : None
pandas                 : 1.4.3
PIL                    : 9.0.1
protobuf               : None
psutil                 : 5.8.0
pytorch-metric-learning: None
pytorch_lightning      : 1.6.5
ray                    : 1.13.0
requests               : 2.28.1
scipy                  : 1.7.3
sentencepiece          : None
setuptools             : 65.3.0
skimage                : 0.19.3
sklearn                : 1.0.2
smart_open             : 5.2.1
timm                   : 0.5.4
torch                  : 1.12.1+cu102
torchmetrics           : 0.7.3
torchtext              : 0.13.1
torchvision            : 0.13.1+cu102
tqdm                   : 4.64.0
transformers           : 4.20.1
xgboost                : 1.4.2
```

</details>

**Comment by yinweisu** [comment]
I think issue 2 is partly fixed by the adding of soft time limit by https://github.com/awslabs/autogluon/pull/2121.
